# Generated by Django 5.2.13 on 2026-04-23 18:45

import django.core.validators
import django.db.models.deletion
import offers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Romance Package', 'Business Travel')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the offer category', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the category name', max_length=100, unique=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for category display (e.g., #FF5722)', max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Offer Category',
                'verbose_name_plural': 'Offer Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the offer (e.g., 'Summer Special 2025')", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500, null=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('package', 'Package Deal'), ('seasonal', 'Seasonal Offer'), ('early_bird', 'Early Bird Discount'), ('last_minute', 'Last Minute Deal'), ('loyalty', 'Loyalty Program'), ('group', 'Group Booking Discount')], default='percentage', max_length=20)),
                ('discount_type', models.CharField(choices=[('room_rate', 'Room Rate Discount'), ('total_booking', 'Total Booking Discount'), ('per_night', 'Per Night Discount'), ('package_price', 'Package Price')], default='room_rate', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, help_text='Package price for package deals', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField(help_text='Start date of the offer')),
                ('valid_to', models.DateField(help_text='End date of the offer')),
                ('minimum_stay', models.PositiveIntegerField(blank=True, help_text='Minimum number of nights required', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_stay', models.PositiveIntegerField(blank=True, help_text='Maximum number of nights allowed', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_advance_booking', models.PositiveIntegerField(blank=True, help_text='Minimum days in advance booking is required', null=True)),
                ('maximum_advance_booking', models.PositiveIntegerField(blank=True, help_text='Maximum days in advance booking is allowed', null=True)),
                ('total_bookings_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of bookings for this offer', null=True)),
                ('bookings_used', models.PositiveIntegerField(default=0, help_text='Number of bookings already made with this offer')),
                ('applies_monday', models.BooleanField(default=True)),
                ('applies_tuesday', models.BooleanField(default=True)),
                ('applies_wednesday', models.BooleanField(default=True)),
                ('applies_thursday', models.BooleanField(default=True)),
                ('applies_friday', models.BooleanField(default=True)),
                ('applies_saturday', models.BooleanField(default=True)),
                ('applies_sunday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured offers appear prominently on the website')),
                ('is_combinable', models.BooleanField(default=False, help_text='Can this offer be combined with other offers')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the offer name', max_length=255, unique=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions for this offer', null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.hotel')),
                ('category', models.ForeignKey(blank=True, help_text='Category this offer belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.offercategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Highlight title (e.g., 'Free Breakfast')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the highlight', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='offers.offer')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Offer promotional image', max_length=500, upload_to=offers.models.offer_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=500, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image displayed in listings')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.offer')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('number_of_guests', models.PositiveIntegerField(help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('preferred_check_in', models.DateField(help_text='Preferred check-in date')),
                ('preferred_check_out', models.DateField(help_text='Preferred check-out date')),
                ('message', models.TextField(blank=True, help_text="Customer's message or special requests", null=True)),
                ('privacy_agreed', models.BooleanField(default=False, help_text='Customer agreed to privacy policy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', help_text='Current status of the application', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offers.offer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer', 'status'], name='offers_offe_offer_i_10809f_idx'), models.Index(fields=['email'], name='offers_offe_email_52f2e8_idx'), models.Index(fields=['created_at'], name='offers_offe_created_44f043_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['hotel', 'is_active'], name='offers_offe_hotel_i_a4976c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_from', 'valid_to'], name='offers_offe_valid_f_072035_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured', 'is_active'], name='offers_offe_is_feat_6c18c1_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['category', 'is_active'], name='offers_offe_categor_10cd3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerhighlight',
            unique_together={('offer', 'title')},
        ),
    ]
