# Generated by Django 5.2.13 on 2026-04-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in currency', max_digits=10)),
                ('currency', models.CharField(default='SAR', help_text='ISO 4217 currency code', max_length=3)),
                ('method', models.CharField(choices=[('tap', 'Tap Payments'), ('bank_transfer', 'Bank Transfer'), ('on_arrival', 'Pay on Arrival')], default='tap', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External provider transaction ID', max_length=100, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Unique request key', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TapPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_id', models.CharField(help_text='Tap charge ID', max_length=100, unique=True)),
                ('tap_source_id', models.CharField(blank=True, help_text='Tap source/card ID', max_length=100, null=True)),
                ('tap_card_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('tap_card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('tap_success', models.BooleanField(default=False)),
                ('tap_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tap_error_message', models.TextField(blank=True, null=True)),
                ('tap_raw_response', models.JSONField(blank=True, default=dict, help_text='Full Tap API response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tap_transaction', to='payments.payment')),
            ],
            options={
                'db_table': 'tap_payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='idx_payment_booking'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='idx_payment_status_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='idx_payment_transaction'),
        ),
        migrations.AddIndex(
            model_name='tappaymenttransaction',
            index=models.Index(fields=['tap_id'], name='idx_tap_id'),
        ),
    ]
