# Generated by Django 5.2.13 on 2026-04-23 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, help_text='Unique booking reference', max_length=30, unique=True)),
                ('guest_first_name', models.CharField(max_length=50)),
                ('guest_last_name', models.CharField(max_length=50)),
                ('guest_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('guest_phone', models.CharField(max_length=30)),
                ('guest_country', models.CharField(max_length=100)),
                ('guest_address', models.TextField()),
                ('guest_city', models.CharField(max_length=100)),
                ('guest_postal_code', models.CharField(max_length=20)),
                ('guest_passport_number', models.CharField(blank=True, max_length=40, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, help_text='Check-in time (default 3:00 PM)', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Check-out time (default 11:00 AM)', null=True)),
                ('nights', models.PositiveIntegerField(editable=False)),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('room_rate', models.DecimalField(decimal_places=2, help_text='Rate per night before taxes', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Room rate × nights', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT and municipality tax', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Member discount or promotional discount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Final amount after taxes and discounts', max_digits=10)),
                ('discount_type', models.CharField(blank=True, help_text="e.g., 'Member Discount', 'Summer Deal'", max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, help_text='Version counter for optimistic locking')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether booking is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion', null=True)),
                ('deleted_reason', models.CharField(blank=True, help_text='Reason for deletion', max_length=500, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Booking Created'), ('status_change', 'Status Changed'), ('payment_status_change', 'Payment Status Changed'), ('details_updated', 'Details Updated'), ('price_adjusted', 'Price Adjusted'), ('refund_issued', 'Refund Issued'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Booking Cancelled'), ('completed', 'Booking Completed'), ('deleted', 'Booking Soft-Deleted'), ('restored', 'Booking Restored')], max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value after change', null=True)),
                ('reason', models.TextField(blank=True, help_text="Reason for the change (e.g., 'Guest requested refund', 'System automation')")),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where change was made', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(help_text='User who made this change (null if system automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_audit_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded to guest', max_digits=10)),
                ('non_refundable_amount', models.DecimalField(decimal_places=2, help_text='Amount retained by hotel', max_digits=10)),
                ('refund_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('refund_method', models.CharField(choices=[('original_payment', 'Original Payment Method'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Hotel Credit'), ('manual', 'Manual (No Auto-Refund)')], default='original_payment', max_length=30)),
                ('refund_reason', models.TextField(help_text='Reason for refund')),
                ('transaction_id', models.CharField(blank=True, help_text='Payment processor transaction ID for refund', max_length=100, null=True)),
                ('refund_requested_at', models.DateTimeField(auto_now_add=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about refund')),
                ('booking', models.OneToOneField(help_text='Associated booking being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='booking_refund', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_refund',
            },
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_cancellation_days', models.PositiveIntegerField(default=1, help_text='Days before check-in when cancellation is free (e.g., 1 = free until 24 hours before)')),
                ('refund_schedule', models.JSONField(default=dict, help_text="Refund % by days before check-in. E.g., {'7': 75, '3': 50, '0': 0}")),
                ('non_refundable_deposit_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of booking that is non-refundable (e.g., 10% service fee)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('policy_description', models.TextField(blank=True, help_text='Human-readable policy description for guests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(help_text='Hotel this policy applies to', on_delete=django.db.models.deletion.CASCADE, related_name='refund_policy', to='core.hotel')),
            ],
            options={
                'db_table': 'refund_policy',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='idx_booking_id'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'status', 'check_in_date', 'check_out_date'], name='idx_room_availability'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='idx_room_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'status'], name='idx_hotel_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'created_at'], name='idx_hotel_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_email'], name='idx_guest_email'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_phone'], name='idx_guest_phone'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date'], name='idx_checkin'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_out_date'], name='idx_checkout'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='idx_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'created_at'], name='idx_payment_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='idx_status_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_deleted'], name='idx_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['booking', 'changed_at'], name='idx_booking_auditlog'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['changed_by', 'changed_at'], name='idx_user_auditlog'),
        ),
        migrations.AddIndex(
            model_name='bookingauditlog',
            index=models.Index(fields=['change_type', 'changed_at'], name='idx_type_auditlog'),
        ),
    ]
