# Generated by Django 5.2.4 on 2025-07-26 07:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('star_rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('check_in_time', models.TimeField(default='15:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('cancellation_policy', models.TextField(default='Free cancellation 24 hours before check-in')),
                ('pet_policy', models.TextField(default='Pets not allowed')),
                ('smoking_policy', models.TextField(default='Non-smoking property')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bed_type', models.CharField(default='Queen Bed', max_length=50)),
                ('bed_count', models.PositiveIntegerField(default=1)),
                ('bathroom_count', models.PositiveIntegerField(default=1)),
                ('room_size_sqm', models.PositiveIntegerField(blank=True, help_text='Room size in square meters', null=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_air_conditioning', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_kitchenette', models.BooleanField(default=False)),
                ('has_minibar', models.BooleanField(default=False)),
                ('has_safe', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=False, help_text='Wheelchair accessible')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Summer Season, Holiday Season', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for base price (1.0 = no change, 1.5 = 50% increase)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('apply_monday', models.BooleanField(default=True)),
                ('apply_tuesday', models.BooleanField(default=True)),
                ('apply_wednesday', models.BooleanField(default=True)),
                ('apply_thursday', models.BooleanField(default=True)),
                ('apply_friday', models.BooleanField(default=True)),
                ('apply_saturday', models.BooleanField(default=True)),
                ('apply_sunday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='core.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='core.roomtype')),
            ],
            options={
                'verbose_name': 'Seasonal Pricing',
                'verbose_name_plural': 'Seasonal Pricing',
                'ordering': ['hotel', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pricing_type', models.CharField(choices=[('per_night', 'Per Night'), ('per_stay', 'Per Stay'), ('per_person', 'Per Person'), ('per_person_night', 'Per Person Per Night')], default='per_stay', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Maximum quantity per booking')),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('parking', 'Parking'), ('wifi', 'WiFi'), ('spa', 'Spa & Wellness'), ('transport', 'Transportation'), ('dining', 'Dining'), ('recreation', 'Recreation'), ('business', 'Business Services'), ('other', 'Other')], default='other', max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Extra Service',
                'verbose_name_plural': 'Extra Services',
                'ordering': ['hotel', 'category', 'name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('floor', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('view_type', models.CharField(choices=[('city', 'City View'), ('sea', 'Sea View'), ('mountain', 'Mountain View'), ('garden', 'Garden View'), ('pool', 'Pool View'), ('courtyard', 'Courtyard View')], default='city', max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['hotel', 'floor', 'room_number'],
                'indexes': [models.Index(fields=['hotel', 'capacity'], name='core_room_hotel_i_29728a_idx'), models.Index(fields=['is_active', 'is_maintenance'], name='core_room_is_acti_eb1a49_idx')],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
    ]
