# Generated by Django 5.2.4 on 2025-08-17 15:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('comfort', 'Comfort'), ('convenience', 'Convenience'), ('entertainment', 'Entertainment'), ('accessibility', 'Accessibility'), ('business', 'Business'), ('family', 'Family'), ('luxury', 'Luxury')], default='comfort', max_length=50)),
                ('icon_class', models.CharField(blank=True, help_text='CSS class for icon display', max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium amenity that may affect pricing')),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='URL to the image')),
                ('image_alt_text', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(choices=[('room_overview', 'Room Overview'), ('bed_area', 'Bed Area'), ('bathroom', 'Bathroom'), ('view', 'View from Room'), ('amenities', 'Amenities'), ('balcony', 'Balcony/Terrace'), ('kitchenette', 'Kitchenette'), ('seating_area', 'Seating Area'), ('entrance', 'Room Entrance'), ('other', 'Other')], default='room_overview', max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image to display in listings')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order to display images (1 = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['room', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_included', models.BooleanField(default=True)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charge for this amenity', max_digits=8)),
            ],
            options={
                'verbose_name': 'Room Type Amenity',
                'verbose_name_plural': 'Room Type Amenities',
            },
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AddField(
            model_name='room',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('needs_renovation', 'Needs Renovation')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='connecting_room',
            field=models.ForeignKey(blank=True, help_text='Connected room for families', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('out_of_order', 'Out of Order'), ('inspected', 'Inspected'), ('maintenance', 'Under Maintenance')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='is_connecting_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_corner_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_inspected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_renovated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='needs_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='renovation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for this specific room'),
        ),
        migrations.AddField(
            model_name='room',
            name='special_features',
            field=models.TextField(blank=True, help_text='Any special features unique to this room'),
        ),
        migrations.AddField(
            model_name='room',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal staff notes about this room'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Room type specific cancellation policy'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium'), ('suite', 'Suite'), ('presidential', 'Presidential'), ('family', 'Family'), ('accessible', 'Accessible')], default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='children_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='early_checkin_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='early_checkin_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_bed_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_bed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge per night for additional bed', max_digits=8),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Main image URL for this room type'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_accessible_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_bathrobes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_bathtub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_blackout_curtains',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_bluetooth_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_braille_signage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_coffee_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_desk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_grab_bars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_hairdryer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_hearing_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_heating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_iron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_ironing_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_lowered_fixtures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_refrigerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_roll_in_shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_seating_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_shower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_slippers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_smart_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_soundproofing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_streaming_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_tea_kettle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_toiletries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_towels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_usb_charging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='infant_bed_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='late_checkout_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='late_checkout_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_children',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='pet_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pet charge per night', max_digits=8),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_size_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Room size in square feet', null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listings', max_length=255),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='360° virtual tour URL'),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_type',
            field=models.CharField(choices=[('city', 'City View'), ('sea', 'Sea View'), ('ocean', 'Ocean View'), ('mountain', 'Mountain View'), ('garden', 'Garden View'), ('pool', 'Pool View'), ('courtyard', 'Courtyard View'), ('park', 'Park View'), ('lake', 'Lake View'), ('river', 'River View'), ('partial_sea', 'Partial Sea View'), ('partial_ocean', 'Partial Ocean View'), ('interior', 'Interior View')], default='city', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single Bed'), ('twin', 'Twin Beds'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('sofa_bed', 'Sofa Bed'), ('bunk_bed', 'Bunk Bed')], default='queen', max_length=50),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['housekeeping_status'], name='core_room_houseke_18caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['view_type'], name='core_room_view_ty_dd47c1_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor'], name='core_room_floor_db7851_idx'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.room'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='If set, this image represents the room type rather than a specific room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.roomtype'),
        ),
        migrations.AddField(
            model_name='roomtypeamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roomamenity'),
        ),
        migrations.AddField(
            model_name='roomtypeamenity',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roomtype'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='additional_amenities',
            field=models.ManyToManyField(blank=True, help_text='Additional amenities for this room type', through='core.RoomTypeAmenity', to='core.roomamenity'),
        ),
        migrations.AlterUniqueTogether(
            name='roomimage',
            unique_together={('room', 'display_order')},
        ),
        migrations.AlterUniqueTogether(
            name='roomtypeamenity',
            unique_together={('room_type', 'amenity')},
        ),
    ]
